apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: sitewatch
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: sitewatch
spec:
  selector:
    app: redis-app
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP

