apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: sitewatch
spec:
  selector:
    matchLabels:
      app: monitoring-svc
  template:
    metadata:
      labels:
        app: monitoring-svc
    spec:
      containers:
        - name: monitoring-svc
          image: bikaxh01/monitoring-svc:93202429f41aa40a122521abcef80d0137e560b4
          volumeMounts:
          - name: secret
            mountPath: /home/app/.env
            subPath: .env
      volumes:
        - name: secret
          secret: 
           secretName: sitewatch-monitoring-secret
           items: 
            - key: .env
              path: .env 

