name: build and push monitoring-svc

on:
  push:
    branches:
      - main
    paths:
      - "monitoring_service/**"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: ./monitoring_service
          file: ./monitoring_service/dockerfile
          push: true
          tags: bikaxh01/monitoring-svc:${{github.sha}}

      - name: update the manifest file
        run: |
          sed -i 's|image: bikaxh01/monitoring-svc:.*|image: bikaxh01/monitoring-svc:${{ github.sha }}|' ops/monitoring_service/deployment.yml

      - name: push the yml change
        run: |
          git config --global user.email "<>"
          git config --global user.name "<monitoring-srv action>"
          git add ops/monitoring_service/deployment.yml
          git commit -m "monitoring-svc-yml changed ${{github.sha}}"
          git push
