name: Hello world

on:
  push:
    branches:
      - main
    paths:
      - "user_management_service/**"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: build image
        run: |
          cd user_management_service 
          docker build -t bikaxh01/sitewatch-backend:${{github.sha}}

      - name: push image
        run: docker push 
