name: Hello world

on:
  push:
    branches:
      - main
    paths:
      - "user_management_service/**"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: ./user_management_service
          file: ./user_management_service/dockerfile
          push: true
          tags: bikaxh01/sitewatch-backend:${{github.sha}}

      - name: update the manifest file
        run: |
           sed -i 's|image: bikaxh01/sitewatch-backend:.*|image: bikaxh01/sitewatch-backend:${{ github.sha }}|' ops/primary-backend/deployment.yml
        
      - name: push the yml change
        run: |
         git config --global user.email "<>"
         git config --global user.name "<primary-backend action>"
         git add ops/primary-backend/deployment.yml
         git commit -m "be-yml changed ${{github.sha}}"
         git push

         


 