name: Hello world

on:
  push:
    branches:
      - main

jobs:
  run-test:
   runs-on: ubuntu-latest
   steps:
     - name: checkout repo
       uses: actions/checkout@v3
     - name: setup node
       uses: actions/setup-node@v3
       with:
         node-version: 18
     - name: install deps
       uses: npm install
     - name: test-completed
       uses: echo test test-completed