name: build and push pub-sub
on:
  push:
    branches:
      - main
    paths:
      - "pub-sub/**"
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: docker login 
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: ./pub-sub
          file: ./pub-sub/dockerfile
          push: true
          tags: bikaxh01/sitewatch-pub-sub:${{github.sha}}

      - name: update the manifest file 
        run: |
            sed -i 's|image: bikaxh01/sitewatch-pub-sub:.*|image: bikaxh01/sitewatch-pub-sub:${{ github.sha }}|' ops/pub-sub/deployment.yml

      - name: push the yml change 
        run: |
          git config --global user.email "<>"
          git config --global user.name "<pub-sub action>"
          git add ops/pub-sub/deployment.yml
          git commit -m "pub-sub-yml changed ${{github.sha}}"
          git push
          


               